# Generated by Django 5.2.7 on 2025-10-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_breed_alter_product_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='description',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='grooming_needs',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='image',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='life_expectancy',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='size',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='temperament',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
