# Generated by Django 5.2.7 on 2025-10-29 16:19

import django.core.validators
import django.db.models.deletion
import shop.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_breed_description_remove_breed_grooming_needs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('color', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Age in months')),
                ('mate_cost', models.DecimalField(decimal_places=2, help_text='Cost for mating service', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mates', to='shop.breed')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mates', to='shop.sellershop')),
            ],
            options={
                'verbose_name': 'Mate',
                'verbose_name_plural': 'Mates',
                'db_table': 'mates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MateImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='mate_images/')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.mate')),
            ],
            options={
                'verbose_name': 'Mate Image',
                'verbose_name_plural': 'Mate Images',
                'db_table': 'mate_images',
            },
        ),
        migrations.CreateModel(
            name='MateVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='mate_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm']), shop.models.validate_video_file_size])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='mate_video_thumbnails/')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='shop.mate')),
            ],
            options={
                'verbose_name': 'Mate Video',
                'verbose_name_plural': 'Mate Videos',
                'db_table': 'mate_videos',
            },
        ),
        migrations.CreateModel(
            name='MateReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mate_reviews', to='shop.mate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mate_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mate Review',
                'verbose_name_plural': 'Mate Reviews',
                'db_table': 'mate_reviews',
                'unique_together': {('mate', 'user')},
            },
        ),
    ]
