# Generated by Django 5.2.7 on 2025-10-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_mate_mateimage_matevideo_matereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mate',
            name='location',
        ),
    ]
