# Generated by Django 5.2.7 on 2025-10-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_mate_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matevideo',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='matevideo',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='matevideo',
            name='thumbnail',
        ),
    ]
